apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: insights-ingress-go
  name: ingress
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ingress
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ingress
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/insights-ingress-go/ingress@sha256:c1d406fbd75ea5940db8d57cc61952ac1e90b01ecd03d3bf5ab1974d4e571d6b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
status: {}
