apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ingress
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/insights-ingress-go/ingress@sha256:c30c01a2766d99d3489e2ae5aee1ab75a5892d0b2c2027feb61be62e26f8e782
        name: container-image
        resources: {}
status: {}
