apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ingress
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/hcc-pipeline-tenant/insights-ingress-go/ingress@sha256:c1d406fbd75ea5940db8d57cc61952ac1e90b01ecd03d3bf5ab1974d4e571d6b
        name: container-image
        resources: {}
status: {}
