apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ingress
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: insights-ingress-go
  name: ingresszphh
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ingress
    weight: 100
status: {}
